---
title: 'Project 2: Energy-Efficiency-Statistical-Analysis, Draft 1'
author: "Christina Mourad, Victor Um, Joe De Leon, Martin Ha"
date: "`r Sys.Date()`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=4, fig.height=3)

```

```{r}
# packages

# install.packages(c("readxl", "ggplot2", "dplyr", "tidyr", "purrr", "corrplot", "infotheo", "caret", "glmnet", "rpart", "rpart.plot", "caTools", "devtools", "nnet"))
#library(ggplot2)
#library(dplyr)
#library(tidyr)
library(readxl)
#library(purrr)
#library(corrplot)
#library(infotheo)
library(caret)
library(car)
#library(glmnet)
#library(rpart)
#library(rpart.plot)
#library(caTools)
#devtools::install_github("gbm-developers/gbm3")
#library(gbm3)
library(tidyverse)
library(nnet)  # For multinomial logistic regression

```

#1. Load Data

- Data Loading and Variable renaming:

```{r}

df <- read_excel("/Users/martinha/Desktop/Math 444/Energy-Efficiency-Statistical-Analysis/ENB2012_data.xlsx")

df <- df %>%
  rename(
    'X1_Relative_Compactness' = X1, 
    'X2_Surface_Area' = X2, 
    'X3_Wall_Area' = X3, 
    'X4_Roof_Area' = X4, 
    'X5_Overall_Height' = X5, 
    'X6_Orientation' = X6, 
    'X7_Glazing_Area' = X7, 
    'X8_Glazing_Area_Distribution' = X8, 
    'Y1_Heating_Load' = Y1, 
    'Y2_Cooling_Load' = Y2
  )

```

- Turn cont. variables into catagorical

```{r}
quantiles <- quantile(df$Y1_Heating_Load, probs = c(0, 0.33, 0.66, 1))

df$Y1_class <- cut(df$Y1_Heating_Load,
                   breaks = quantiles,
                   labels = c("Low", "Medium", "High"),
                   include.lowest = TRUE)


summary(df$Y1_Heating_Load[df$Y1_class == "Low"])
summary(df$Y1_Heating_Load[df$Y1_class == "Medium"])
summary(df$Y1_Heating_Load[df$Y1_class == "High"])
table(df$Y1_class)
```

## Multinom. Model for Y1

```{r}
model <- multinom(Y1_class ~ X1_Relative_Compactness + X2_Surface_Area + X3_Wall_Area + 
                  X5_Overall_Height + X6_Orientation + X7_Glazing_Area, data = df)
#vif(model)
#summary(model)
```

- Predict

```{r}
predictions <- predict(model, df)
```

- AIC/BIC Values

```{r}
aic_value <- AIC(model)
print(paste("AIC:", aic_value))

# Calculate BIC
bic_value <- BIC(model)
print(paste("BIC:", bic_value))
```

- Confusion Matrix

```{r}
predicted_classes <- predict(model, newdata = df, type = "class")
conf_matrix <- confusionMatrix(predicted_classes, df$Y1_class)
print(conf_matrix)
```

## Multinom. Model for Y2

```{r}
quantiles <- quantile(df$Y2_Cooling_Load, probs = c(0, 0.33, 0.66, 1))

df$Y2_class <- cut(df$Y2_Cooling_Load,
                   breaks = quantiles,
                   labels = c("Low", "Medium", "High"),
                   include.lowest = TRUE)


summary(df$Y2_Cooling_Load[df$Y2_class == "Low"])
summary(df$Y2_Cooling_Load[df$Y2_class == "Medium"])
summary(df$Y2_Cooling_Load[df$Y2_class == "High"])
table(df$Y2_class)
```

```{r}
model2 <- multinom(Y2_class ~ X1_Relative_Compactness + X2_Surface_Area + X3_Wall_Area + 
                  X5_Overall_Height + X6_Orientation + X7_Glazing_Area, data = df)
#vif(model)
#summary(model)
```
```{r}
predictions <- predict(model2, df)
```

```{r}
aic_value2 <- AIC(model2)
print(paste("AIC:", aic_value2))

# Calculate BIC
bic_value2 <- BIC(model2)
print(paste("BIC:", bic_value2))
```

```{r}
predicted_classes2 <- predict(model2, newdata = df, type = "class")
conf_matrix2 <- confusionMatrix(predicted_classes2, df$Y1_class)
print(conf_matrix2)
```
